---
- name: Add user ip time to bash/ksh history
  hosts: all
  remote_user: root
  gather_facts: no
  vars:
    histfilesize: '20000'
    histsize: '2000'
    histsh: '/etc/profile.d/hist.sh'
  tasks:
  - name: Add hist.sh global profile
    file: path={{ histsh }} state=touch owner=root group=root mode=0644
    tags: 
    - bash

  - name: Edit hist.sh global profile
    lineinfile: dest={{ histsh }} line={{ item }} state=present
    with_items:
    - HISTFILESIZE={{ histfilesize }}
    - HISTSIZE={{ histsize }}
    - "'HISTIGNORE=\"\"'"
    - "'HISTCONTROL=\"\"'"
    - "'readonly HISTFILE'"
    - "'readonly HISTCMD'"
    - "'readonly HISTSIZE'"
    - "'readonly HISTFILESIZE'"
    - "'readonly HISTIGNORE'"
    - "'readonly HISTCONTROL'"
    - "'PROMPT_COMMAND=\"${PROMPT_COMMAND:-:} ; history -a\"'"
    - "'export HISTSIZE HISTFILESIZE HISTIGNORE HISTCONTROL PROMPT_COMMAND'"
    - "'shopt -s histappend'"
    tags:
    - bash

  - name: Edit hist.sh global profile, cont 
    lineinfile: dest={{ histsh }} state=present line="export HISTTIMEFORMAT=\"$LOGNAME `echo $SSH_CLIENT | awk {'print $1'}` %F %T \""
    tags:
    - bash

  - name: Source hist.sh profile
    shell: source /etc/profile.d/hist.sh
    tags:
    - bash

  - name: Add chattr to history files
    shell: find / -maxdepth 4 -name '*sh_history' -print | xargs chattr +a
    tags:
    - bash
    - ksh

  - name: Find ksh users
    shell: grep ksh /etc/passwd | cut -d':' -f6
    register: kshusers
    tags:
    - ksh
    
  - name: Add .kshrc profile
    file: path={{ item }}/.kshrc state=touch owner=root group=root mode=0644
    with_items: kshusers.stdout_lines
    tags:
    - ksh

  - name: Edit kshrc profile
    lineinfile: dest={{ item }}/.kshrc line="PS1='$(printf \"%(# %D %T )T\" | read -s)$ '" state=present
    with_items: kshusers.stdout_lines
    tags:
    - ksh
