---
- name: Tweaking IBM DB2 sysctl kernel parameters
  hosts: all
  remote_user: root

  tasks:
  - name: Add common sysctl parameter
    sysctl: name={{ item.name }} value={{ item.value }} ignoreerrors=yes
	with_items:
	  - { name: "vm.swappiness", value: "0" }
	  - { name: "vm.overcommit_memory", value: "0" }
	  - { name: "kernel.msgmax", value: "65536" }
	  - { name: "kernel.msgmnb", value: "65536" }
	tags:
	  - common
	
  - name: Add memory-related sysctl parameter
    sysctl: name={{ item.name }} value={{ item.value }} ignoreerrors=yes
	with_items:
	  - { name: "kernel.shmmni", value: "4096" }
	  - { name: "kernel.sem", value: '"250 256000 32 4096"' }
	  - { name: "kernel.shmmax", value: "15462000000" }
	  - { name: "kernel.shmall", value: "3355000" }
	  - { name: "kernel.msgmni", value: "16384" }
	tags:
	  - 16G
	
  - name: Add memory-related sysctl parameter
    sysctl: name={{ item.name }} value={{ item.value }} ignoreerrors=yes
	with_items:
	  - { name: "kernel.shmmni", value: "8192" }
	  - { name: "kernel.sem", value: '"250 256000 32 8192"' }
	  - { name: "kernel.shmmax", value: "30924000000" }
	  - { name: "kernel.shmall", value: "6710000" }
	  - { name: "kernel.msgmni", value: "32768" }
	tags:
	  - 32G