---
- name: Extend available vg to data lv
  hosts: all
  remote_user: root

  tasks:
  - name: scan device
    shell: echo '- - -' > /sys/class/scsi_host/host0/scan

  - name: extend rootvg on /dev/sdb
    lvg: vg=rootvg pvs=/dev/sda2,/dev/sdb

  - name: extend datalv to all free vgs
    command: lvextend -l +100%FREE /dev/rootvg/datalv

  - name: resize datalv
    command: resize2fs /dev/rootvg/datalv
