---
- name: install db2 req.
  hosts: all
  remote_user: root
  tasks:
#  - name: Delete redhat.repo
#    file: dest=/etc/yum.repos.d/redhat.repo state=absent

  - name: List other repos
    shell: ls -1 /etc/yum.repos.d/*
    register: repos
    when: ansible_architecture == "x86_64"

  - name: Delete original repo
    file: dest={{ item }} state=absent
    with_items: repos.stdout_lines
    when: ansible_architecture == "x86_64"

#  - name: Disable other repos
#    lineinfile: dest={{ item }} regexp=^.nabled= state=absent
#    with_items: repos.stdout_lines

#  - name: Disable other repos2
#    lineinfile: dest={{ item }} regexp=^enabled= line=enabled=0
#    with_items: repos.stdout_lines

  - name: Copy the repo conf
    copy: src=dev/rhel5x64dev.repo dest=/etc/yum.repos.d/
    when: ansible_architecture == "x86_64"

  - name: Install the pkg
    yum: pkg={{ item }} state=present enablerepo=rhel5x64
    with_items:
      - pam
      - pam.i686
      - libstdc++
      - libstdc++.i686
      - compat-libstdc++-33
      - compat-libstdc++-33.i686
      - libaio
      - libaio.i686
    when: ansible_architecture == "x86_64"
