---
# this is an example of how to run repeated task elements over lists
# of items, for example, installing multiple packages or configuring
# multiple users

- hosts: all
  user: root

  tasks:

  - name: install packages
    action: yum name={{ item }} state=installed
    with_items:
       - cobbler
       - httpd

  - name: configure users
    action: user name={{ item }} state=present groups=wheel
    with_items:
       - testuser1
       - testuser2

  - name: remove users
    action: user name={{ item }} state=absent
    with_items:
        - testuser1
        - testuser2



