---
- name: Build hosts file
  hosts: all
  remote_user: root
  
  tasks:
  - name: Touch hosts.1 file
    file: path=/etc/hosts.1 state=touch owner=root group=root mode=0644
  
  - name: Build hosts file
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_fqdn }}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['all']